### ISSUE TITLE
Update CHWS given new data

### ISSUE THREAD

**Issue by samgdotson** [arfc/pride#150]
Now that we have new data about chilled water, we should update the model to reflect this.
1. Create a new end use demand (chilled water measured in tons) (should increase by 1% like all other demands)
2. The technology CHWS should use electricity and produce chilled water (for now we will ignore steam chillers because they aren't really used right now and the data doesn't distinguish -- similar to how Abbott is modeled as a gas plant only).
3. Efficiency should be updated (different from one...)

Data can be found in 2019 Energy Data.xlsx in the Box folder

**Comment by robfairh** [comment]
Update the geothermal system as well.
