### ISSUE TITLE
Understand Temoa's results

### ISSUE THREAD

**Issue by robfairh** [arfc/pride#155]
Here are some the results for Temoa's current models:

```UIUC_2050_cost```:

Figure 1:
![cost scenario_all_emissions_co2eq](https://user-images.githubusercontent.com/43791150/108208943-7023bf00-7108-11eb-82af-6e9ba71c960b.png)

Figure 2:
![cost scenario_ind_generation](https://user-images.githubusercontent.com/43791150/108211551-91d27580-710b-11eb-9dcd-64a4ec1d6531.png)

Figure 3:
![cost scenario_elc_generation](https://user-images.githubusercontent.com/43791150/108211475-7cf5e200-710b-11eb-923f-4981debca2a0.png)

Figure 4:
![cost scenario_ind_capacity](https://user-images.githubusercontent.com/43791150/108211644-b2023480-710b-11eb-9f61-9919f9a394d9.png)

* Issue number 1:
Figure 1 shows that the CO2 emission falls to zero.
Figure 2 is consistent with this behavior.
However, Figure 3 is not. ```TURBINE``` produces electricity somehow without producing CO2. If ```TURBINE``` produces electricity means that ```ABBOTT``` is producing ```STM```. However, Figure 2 shows that ```ABBOTT doesn't produce ```STM```. The only explanation I find is that Temoa is accumulating ```STM```.

* Issue number 2:
Figure 4 shows that ABBOTT's capacity is more than 375 MWth in 2021. The model imposes that constraint for all the future years including 2021. The rest of the years seem to meet this constraint.

```UIUC_2050_land```:

Figure 1:
![land scenario_all_emissions_co2eq](https://user-images.githubusercontent.com/43791150/108211404-694a7b80-710b-11eb-885c-5f87fba04f21.png)

Figure 2:
![land scenario_ind_generation](https://user-images.githubusercontent.com/43791150/108211547-8ed78500-710b-11eb-8556-e2ac386bba24.png)

Figure 3:
![land scenario_elc_generation](https://user-images.githubusercontent.com/43791150/108211512-841cf000-710b-11eb-8c42-7708d1c916e2.png)

* Issue number 3: similar to number 1 but for the land-use model.

This issue can be closed when an explanation for these phenomena is found and the 3 issues are fixed.

**Comment by yardasol** [comment]
hmm this one's a doozy

**Comment by samgdotson** [comment]
This isn't so bad. 

1. We should get rid of the minimum activity for wind after 2026. That's when the university's actual PPA ends. 
2. I'm actually not bothered by the fact that the cost scenario adds so much wind power. This just means that Temoa believes it is in the University's interest to obtain more PPAs. The results would likely be different if UIUC had to pay a fixed cost for wind and solar energy. Bottom line, this is okay. 
3. To solve the TURBINE issue. Try adding a small but non-zero amount of carbon emissions from the Turbine. Perhaps 0.00001 tons/GWh (whatever the units are, I'm forgetting). This should force Temoa to stop using the TURBINE to generate electricity.

**Comment by samgdotson** [comment]
Update: @robfairh and I solved the TURBINE problem. ``data_parser`` was combining TURBINE and NTURBINE. We have renamed NTURBINE "SPINNY" for the moment, to prevent string overlap. Here is the new result:
![costScenario_elc_generation](https://user-images.githubusercontent.com/44342873/108254155-470f2880-7120-11eb-869c-818ea964cc01.png)

**Comment by yardasol** [comment]
@samgdotson Can you PR your fixes?

**Comment by robfairh** [comment]
PR #156 partially fixes this issue.

**Comment by robfairh** [comment]
> * Issue number 1:
>   Figure 1 shows that the CO2 emission falls to zero.
>   Figure 2 is consistent with this behavior.
>   However, Figure 3 is not. `TURBINE` produces electricity somehow without producing CO2. If `TURBINE` produces electricity means that `ABBOTT` is producing `STM`. However, Figure 2 shows that `ABBOTT` doesn't produce `STM`. The only explanation I find is that Temoa is accumulating `STM`.

PR #156 partially fixes this issue, by solving the above-called issue number 1.

**Comment by robfairh** [comment]
* Issue number 3:
PR #156 unveiled another issue. `Turbine` and `Nbine` are dummy technologies with no associated cost. As they have no cost, they are free and Temoa deploys too much capacity for them. The following figures highlight this issue for the `Nbine` technology.

Figure 1 and 2 show the capacity and the generation respectively.
While the capacity is around 400 MW, the generation is only 200 GWh, meaning that an `Nbine` of only 23 MW would suffice.

Figure 1:
![capacity](https://user-images.githubusercontent.com/43791150/109293222-41919c80-780a-11eb-9549-6cd44cf64485.png)

Figure 2:
![generation](https://user-images.githubusercontent.com/43791150/109293227-43f3f680-780a-11eb-8a40-dbed2f5c6036.png)
`

**Comment by robfairh** [comment]
> * Issue number 2:
>   Figure 4 shows that ABBOTT's capacity is more than 375 MWth in 2021. The model imposes that constraint for all the future years including 2021. The rest of the years seem to meet this constraint.

This issue number 2 is addressed in a new issue: #162.
Closing this issue.
