### ISSUE TITLE
Update the ANS abstract

### ISSUE THREAD

**Issue by samgdotson** [arfc/pride#21]
This issue can be closed when the following items have been updated: 
- [x] Figures (replace typical figures with typical/synthetic figures). 
- [x] Introduction/Methodology (anywhere that says I'm not working on Steam...)
- [x] Update the simplifying assumption from MWe baseload power to MWth "baseload" (this way the reactor can supply steam OR electricity). 
- [x] Add the assumption that steam be delivered at 325 PSI (this replaces the steam produced by gas turbines).

**Comment by katyhuff** [comment]
Status?

**Comment by samgdotson** [comment]
This issue should have been closed in february... I don't remember which PR closed it.

**Comment by samgdotson** [comment]
Closed by #34
