### ISSUE TITLE
Convert rail splitter data from spreadsheet to csv

### ISSUE THREAD

**Issue by samgdotson** [arfc/pride#32]
This issue can be closed when a file called ``railsplitter-data.csv`` has been uploaded to Box (or sent to Sam) that has two columns ``Date and Time`` and ``Buyer's Share`` where the latter refers to the actual MWh delivered to the UIUC campus for a given hour by Rail Splitter Wind Farm.

**Comment by Dayvis7** [comment]
Closed by Uploading to Box
