### ISSUE TITLE
ANS Abstract: Katy Review

### ISSUE THREAD

**Issue by samgdotson** [arfc/pride#69]
Attached is the draft of the ANS Abstract after Gavin's review.

[main.pdf](https://github.com/arfc/pride/files/4852715/main.pdf)

**Comment by katyhuff** [comment]
[dotson.pdf](https://github.com/arfc/pride/files/4855500/dotson.pdf)


Lots of items from the writing checklist should be reviewed again.

- [ ] Other misused/overused words include: code, input, output, different, value, amount, model.
- [ ] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [ ] reduce vague words (important, methodological) 
- [ ] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [ ] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [ ] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [ ] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") (management of power systems -> power systems management, to the task of net load prediction -> to predict net load, the task of net load forecasting -> to forecast net load)
- [ ] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [ ] Always use isotopic notation like `$^{239}Pu$`. Never $Pu-239$ or plutonium-239.
- [ ] A phrase of the form <verb>ion of <noun> is probably clearer as <noun> <verb>ion. (For example, convert "calculation of velocity" to "velocity calculation".)
- [ ] Cite all software. Review [the principles](https://www.force11.org/software-citation-principles) and try [CiteAs](https://citeas.org/about) if necessary.
- [ ] Refer to software consistently by name.

**Additional Table and Figure Checklist:**

- [ ] When referring to figures by their number, use `Figure 1` and `Table 1.` They should be capitalized and not abbreviated (not `fig. 1` or `figure 1`.)

**Additional Math Comments**

- [ ] define all variables, with units. If unitless, indicate that this is the case `$[-]$`.
- [ ] Variables should be defined in the `align` environment as well, not buried in paragraphs.
Here’s an example of an equation:

```tex
The line is defined as
\begin{align}
y&=mx + b
\intertext{where}
y&= \mbox{ height of the line, also known as rise [m]}\nonumber\\
m&= \mbox{ slope [-]}\nonumber\\
x&=\mbox{ independent parameter, known as run [m]}\nonumber\\
b&= \mbox{ y intercept [m].}
\end{align}
```

**Comment by katyhuff** [comment]
I am going to close this issue (because my review is now complete). But, I'll open a new issue, assigned to you (@samgdotson), which can be closed with updates to the paper.
