### ISSUE TITLE
fix labels in temoa_processing notebook

### ISSUE THREAD

**Issue by robfairh** [arfc/pride#83]
Currently, the figures in [this](https://github.com/arfc/pride/blob/master/temoa-uiuc/temoa_processing.ipynb) notebook look like this:

![image](https://user-images.githubusercontent.com/43791150/88198229-1e19ca00-cc09-11ea-9f91-cd4626c01158.png)

This issue can be closed when a PR fixes the labels.
Some possibilities are making the bars wider or rotating the labels slightly.

**Comment by samgdotson** [comment]
This issue is a duplicate of #84 (@robfairh and I created these issues simultaneously). 

Closing
